Adding inline script

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,12 +4,13 @@ description: 'Peek into the env passed to action'
 runs:
   using: 'composite'
   steps:
-    - name: list-folder-contents
-      run: ls
-      shell: bash
-    - name: find-script
-      run: find . | grep check-pr-title.sh
-      shell: bash
     - name: check-pr-title-for-jira-issue
-      run: ./check-pr-title.sh
+      run: |
+        PR_URL=$(echo $GITHUB_CONTEXT | jq -r ".event.pull_request.title")
+        if [ -z "$PR_TITLE" ]; then
+            echo "Found Jira issue ID: $(echo $PR_TITLE | grep -o "GRUB-\d*")
+        else
+            echo "::Error: No Jira issue ID found!
+            exit 1
+        fi
       shell: bash
